fix: hasOwn not found
fent/muk-prop.js pull request #13
Opened 2023-05-10 04:13 UTC by gemwuu

An `obj` created by `Object.create(null)` doesn't has `hasOwn` or `hasOwnProperty` method.

2023-05-10 05:08 UTC, fengmk2 approved these changes
LGTM

2023-05-10 06:23 UTC, fent requested changes
Thanks for your contribution! I left a couple of comments

2023-05-10 06:23 UTC, fent commented on test/method-test.js
> +
place this inside of the `it`

2023-05-10 06:23 UTC, fent commented on package.json
>    "main": "./lib/index.js",
please revert changes to this file

2023-05-10 06:28 UTC, gemwuu commented
> Thanks for your contribution! I left a couple of comments

It's my pleasure! This repo helps us a lot!

2023-05-10 14:09 UTC, popomore approved these changes
LGTM

2023-05-11 00:13 UTC, fent approved these changes

2023-05-11 00:16 UTC, merged

2023-05-11 03:53 UTC, popomore commented
@fent It seem that we should release a major version, because you had upgrade node version in some commits.

2023-05-12 02:14 UTC, popomore commented
I have released v3.0.0

2023-05-12 02:43 UTC, fent commented
Thanks for that. Let me see if I can figure out how to list them on Releases