feat: add Map and Set support
fent/muk-prop.js pull request #14
Opened 2023-05-12 09:57 UTC by gemwuu

2023-05-12 10:04 UTC, fengmk2 approved these changes
+1

2023-05-13 19:32 UTC, fent commented on lib/index.js
> + * @param {!Function|Object|Map|Set|String} value
this can be changed to just `Object` as that covers everything

2023-05-13 19:32 UTC, fent requested changes
ah interesting, nice catch!

2023-05-14 09:09 UTC, fent requested changes
i don't think it's necessary to include examples in the readme about mocking Map/Set. these are edge cases that i wouldn't think many users would find useful when they're trying to learn how to use the library

2023-05-14 09:13 UTC, gemwuu commented
> i don't think it's necessary to include examples in the readme about mocking Map/Set. these are edge cases that i wouldn't think many users would find useful when they're trying to learn how to use the library

fair enough, the `README.md` modification has been reverted.

2023-05-14 09:13 UTC, fent approved these changes

2023-05-14 09:18 UTC, merged

2023-05-14 09:21 UTC, fent commented
thanks again! @popomore can you create a patch release for this? if not, i can do it late sunday/monday as i'm away from my computer right now

2023-05-15 04:43 UTC, popomore commented
@fent I have released 3.0.1